/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Physical AI & Humanoid Robotics",
  "tagline": "From Digital Intelligence to Embodied Systems",
  "favicon": "img/favicon.ico",
  "url": "https://your-username.github.io",
  "baseUrl": "/my-ai-book-hackathon/",
  "organizationName": "your-username",
  "projectName": "my-ai-book-hackathon",
  "onBrokenLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "Physical AI & Humanoid Robotics",
      "logo": {
        "alt": "Physical AI Book Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Book"
        },
        {
          "href": "https://github.com/facebook/docusaurus",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "katex": {
      "macros": {
        "\\R": "\\mathbb{R}",
        "\\SE": "\\mathrm{SE}",
        "\\SO": "\\mathrm{SO}",
        "\\q": "\\mathbf{q}",
        "\\dq": "\\dot{\\mathbf{q}}",
        "\\ddq": "\\ddot{\\mathbf{q}}",
        "\\tau": "\\boldsymbol{\\tau}",
        "\\J": "\\mathbf{J}",
        "\\T": "\\mathbf{T}",
        "\\p": "\\mathbf{p}",
        "\\Rmat": "\\mathbf{R}",
        "\\I": "\\mathbf{I}",
        "\\M": "\\mathbf{M}",
        "\\C": "\\mathbf{C}",
        "\\G": "\\mathbf{G}",
        "\\x": "\\mathbf{x}",
        "\\u": "\\mathbf{u}",
        "\\y": "\\mathbf{y}",
        "\\K": "\\mathbf{K}",
        "\\A": "\\mathbf{A}",
        "\\B": "\\mathbf{B}",
        "\\Cmat": "\\mathbf{C}",
        "\\D": "\\mathbf{D}",
        "\\Q": "\\mathbf{Q}",
        "\\P": "\\mathbf{P}",
        "\\Kmat": "\\mathbf{K}",
        "\\z": "\\mathbf{z}"
      }
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Book Chapters",
          "items": [
            {
              "label": "Chapter 1: Foundations",
              "to": "/docs/category/chapter-1-foundations"
            },
            {
              "label": "Chapter 2: ROS 2",
              "to": "/docs/category/chapter-2-ros-2"
            },
            {
              "label": "Chapter 3: Simulation",
              "to": "/docs/category/chapter-3-simulation"
            }
          ]
        },
        {
          "title": "Advanced Topics",
          "items": [
            {
              "label": "Chapter 4: NVIDIA Isaac",
              "to": "/docs/category/chapter-4-nvidia-isaac"
            },
            {
              "label": "Chapter 5: Autonomous Systems",
              "to": "/docs/category/chapter-5-autonomous-systems"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/your-username/my-ai-book-hackathon"
            },
            {
              "label": "ROS 2",
              "href": "https://docs.ros.org/en/humble/"
            },
            {
              "label": "NVIDIA Isaac",
              "href": "https://docs.omniverse.nvidia.com/"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Physical AI Book Project. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "python",
        "bash",
        "yaml",
        "cpp"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
