name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Replace placeholders with your actual info
          git push --force https://burair-ahmed:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/burair-ahmed/ai-book-with-rag-chatbot main
